services:
    Isotope\Controller\PostsaleController:
        arguments:
            - '@contao.framework'
            - '@uri_signer'
        tags:
            - { name: controller.service_arguments }

    Isotope\Controller\ProductHitController:
        arguments:
            - '@database_connection'
            - '%kernel.secret%'
        tags:
            - { name: controller.service_arguments }

    isotope.listener.symlink:
        class: Isotope\EventListener\SymlinkListener
        arguments:
            - '%kernel.project_dir%'
            - '%contao.web_dir%'
            - '@?filesystem'
        tags:
            - { name: kernel.event_listener, event: contao.generate_symlinks }

    isotope.listener.frontend_preview:
        class: Isotope\EventListener\FrontendPreviewListener
        tags:
            - { name: kernel.event_listener, event: contao.preview_url_create, method: onPreviewUrlCreate }

    isotope.picker.product:
        class: Isotope\Picker\ProductPickerProvider
        arguments:
            - '@contao.framework'
            - '@knp_menu.factory'
            - '@router'
            - '@translator'
            - '@database_connection'
        tags:
            - contao.picker_provider

    isotope.fragment.registry:
        alias: contao.fragment.registry
        public: true

    isotope.unit_converter:
        class: UnitConverter\UnitConverter
        arguments:
            - '@isotope.unit_registry'
            - '@isotope.binary_calculator'
        public: true

    isotope.unit_registry:
        class: UnitConverter\Registry\UnitRegistry
        arguments:
            - ['@unit.milligram', '@unit.gram', '@unit.kilogram', '@unit.ounce', '@unit.pound', '@unit.stone']

    unit.milligram:
        class: UnitConverter\Unit\Mass\Milligram
    unit.gram:
        class: UnitConverter\Unit\Mass\Gram
    unit.kilogram:
        class: UnitConverter\Unit\Mass\Kilogram
    unit.ounce:
        class: UnitConverter\Unit\Mass\Ounce
    unit.pound:
        class: UnitConverter\Unit\Mass\Pound
    unit.stone:
        class: UnitConverter\Unit\Mass\Stone

    isotope.binary_calculator:
        class: UnitConverter\Calculator\BinaryCalculator
        arguments:
            - 2 # Precision
            - 1 # PHP_ROUND_HALF_UP - Rounding mode

    Isotope\Weight:
        arguments: ['@isotope.unit_converter']
